### ISSUE TITLE
down load problem with Signac 

### ISSUE THREAD

**Issue by zh-zhang1984** [mathewchamberlain/SignacX#11]
I found the following download link is not available for me; is there any method to store the data file with the package? after loading the package, I can have access to the training data.
```
> labels <- Signac(SeuratIntegrate, num.cores = 4)
Error in url("https://github.com/mathewchamberlain/SignacX/blob/master/assets/training_HPCA.rds?raw=TRUE",  : 
  cannot open the connection to 'https://github.com/mathewchamberlain/SignacX/blob/master/assets/training_HPCA.rds?raw=TRUE'
In addition: Warning message:
In url("https://github.com/mathewchamberlain/SignacX/blob/master/assets/training_HPCA.rds?raw=TRUE",  :
  URL 'https://raw.githubusercontent.com/mathewchamberlain/SignacX/master/assets/training_HPCA.rds': status was 'Couldn't connect to server'
> P = GetTrainingData_HPCA()
Warning in url("https://github.com/mathewchamberlain/SignacX/blob/master/assets/training_HPCA.rds?raw=TRUE",  :
  URL 'https://github.com/mathewchamberlain/SignacX/blob/master/assets/training_HPCA.rds?raw=TRUE': Timeout of 60 seconds was reached
Error in url("https://github.com/mathewchamberlain/SignacX/blob/master/assets/training_HPCA.rds?raw=TRUE",  : 
  cannot open the connection to 'https://github.com/mathewchamberlain/SignacX/blob/master/assets/training_HPCA.rds?raw=TRUE'
```

**Comment by mathewchamberlain** [comment]
Hi there,

I was not able to reproduce this error using SignacX 2.2.2. However, you might have problems accessing data due to your server settings. You can try this:

git clone https://github.com/mathewchamberlain/SignacX.git

The reference data is in the 'assets' folder. You can read it into R:

Ref = readRDS('assets/training_HPCA.rds')

And then use it in Signac by setting the "R" parameter:

labels <- Signac(SeuratIntegrate, num.cores = 4, R = Ref)

Let me know if this works -- if I do not hear from you, I will close the issue in a few days.

Mat

**Comment by mathewchamberlain** [comment]
I might also suggest checking your firewall settings or leaving the VPN. If you do that, you can probably just run the code as usual.

**Comment by zh-zhang1984** [comment]
I still fail to download this file; I think the problem is that the webservier from our location banned the connection.

**Comment by zh-zhang1984** [comment]
Can you help me to get this file by sending via email?   zh_zhang1984@zju.edu.cn
I really want to apply your method for my current project, and have struggle for a long while to download this file.

**Comment by mathewchamberlain** [comment]
I just sent it via a Google Drive link, let me know if that works. If I do not hear from you, I will close the issue in a few days.

**Comment by zh-zhang1984** [comment]
Yes, I can obtain the dataset; thank you very much1
