### ISSUE TITLE
SignacX-MASC vignette

### ISSUE THREAD

**Issue by algarji** [mathewchamberlain/SignacX#2]
Hi, I am trying to complete this [vignette](https://mathewchamberlain.github.io/SignacX/articles/signac-Seurat_AMP.html), but I don't know how  to obtain the counts and metadata files from the kidney experiment ('SDY997_EXP15176_celseq_matrix_ru10_molecules.tsv.gz' and 'SDY997_EXP15176_celseq_meta.tsv'). I would like to use this example dataset in order to explore the code on my own and fully understand the workflow. Thank you.

**Comment by mathewchamberlain** [comment]
Those datasets are available from the original publication:

https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6726437/
