### ISSUE TITLE
Cholmod error 'problem too large'

### ISSUE THREAD

**Issue by pcallen225** [mathewchamberlain/SignacX#5]
When using Signac/SignacFast after integrating a large dataset ~325k cells with Harmony, I'm getting this error. Is there a way around it? I'm using 8 cores each with 200gb of memory. 

<img width="873" alt="image" src="https://user-images.githubusercontent.com/47501726/120721038-b1ab6080-c492-11eb-95a6-1834ea3e7265.png">

`..........  Entry in SignacFast 
 ..........  Running SignacFast on Seurat object :
             nrow = 36601
             ncol = 325267
Error in A %*% (A %^% (n - 1)): Cholmod error 'problem too large' at file ../Core/cholmod_sparse.c, line 89
Traceback:

1. SignacFast(merged.dataset, num.cores = 8)
2. CID.GetDistMat(edges)
3. m %^% j
4. A %*% (A %^% (n - 1))
5. A %*% (A %^% (n - 1))`

**Comment by mathewchamberlain** [comment]
I was able to classify >300,000 cell datasets using Signac + SignacFast across 8 cores on a 512 GB RAM AWS instance -- closing this issue for now.

**Comment by mathewchamberlain** [comment]
SignacX 2.2.4 (on CRAN tomorrow or the next day) has fixed this problem. Thanks for bringing it up @pcallen225. Please try using SignacFast with ~4-12 cores.
